/**
 * generated by Xtext 2.25.0
 */
package dsl;

import dsl.GreenhouseStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GreenhouseStandaloneSetup extends GreenhouseStandaloneSetupGenerated {
  public static void doSetup() {
    new GreenhouseStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
